# Generated by Django 4.2.7 on 2024-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_categoria_libroscategorias_libro_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
